### PR TITLE
Cleanup of your project

### PR DESCRIPTION
**Pull request by nimarion**
* Improved .gitignore
* Removed unnecessary files and folders which dont belong to github repo

### CODE REVIEW

**Comment by FultonBrowne** [comment]
Thank you for contributing, can you make one change, can you remove the exclusion of jar files for now, I am dealing with a quirk in my cloud service where it has to have that jar file prebuilt in the repo, I am working on it, (maybe you could set the artifact jar to build on gradle build?) could you undo the exclude of jar files?

**Comment by nimarion** [comment]
You can bypass the exclusion of the jar files in .gitignore: 

> git add --force -- file1 file2
git commit -m "your message"
git push

Why is your cloud service having a problem when the jar is not included in the repo?

**Comment by FultonBrowne** [comment]
It Gradle build every time I deploy from the code in the repo ,(I linked those together) I can not get Gradle to build the artifact for whatever reason, so I upload the artifact with the rest of the repo, I also have api keys and DB credentials that I can build in to the jar but leave out of the published source code.

**Comment by nimarion** [comment]
When you build the jar with the credentials you can decompile the jar and search them in the code. Please use enviroment variables or some kind of configuration file. Also please check out a Java style guide to improve the structure of the current project 🙊
If you want i can have a look at it tomorrow ^^

**Review by FultonBrowne — APPROVED** [review]
thanks for the code I will look at your suggestions and improve security of the API keys

**Comment by FultonBrowne** [comment]
you may want to see this https://github.com/FultonBrowne/Ara-Server/commit/08b1322b12c18517d26a9d1eb6479a8dc7feb639/checks

**Pull request closed without merging**
